### ISSUE TITLE
Is anyone else still getting the HTTPError 502 Bad Gateway? Please help

### ISSUE THREAD

**Issue by gsichali** [alexa/skill-sample-python-smarthome-iot#18]
An error occurred during JSON serialization of response: <HTTPError 502: 'Bad Gateway'> is not JSON serializable
Traceback (most recent call last):
  File "/var/lang/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/var/lang/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/var/lang/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/var/runtime/awslambda/bootstrap.py", line 149, in decimal_serializer
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <HTTPError 502: 'Bad Gateway'> is not JSON serializable

**Comment by evaltierra** [comment]
You have to update your SampleEndpointAdapter Lambda if you followed Manual steps.

Got to https://github.com/alexa/skill-sample-python-smarthome-sandbox/tree/master/lambda/api/endpoint_cloud and copy the latest api_handler_directive.py, api_handler_endpoint.py, api_handler_event.py files on your Lambda. The files are under endpoint_cloud folder. After saving these changes the PowerController events will work properly.

Also check your DynamoDB Key, if it is "DetailsId" instead of "EndpointId" update the lambda code accordingly.

**Comment by haroon3rd** [comment]
You also have to update your api_utils.py in SampleEndpointAdapter Lambda if you followed Manual steps. It is missing the static method 'check_response(response)'

So.. what you need to do is: 
Got to https://github.com/alexa/skill-sample-python-smarthome-sandbox/tree/master/lambda/api/endpoint_cloud
copy the latest 
api_handler_directive.py, 
api_handler_endpoint.py, 
api_handler_event.py, and
api_utils.py
files on your Lambda. The files are under the endpoint_cloud folder. After saving these changes the PowerController events will work properly. However, you might get a 'namespace" key error.

Add "namespace":"Alexa.PowerController" in 'POST/events (ChangeReport)' in postman and anywhere else you get this error. 

Also check your DynamoDB Key, if it is "DetailsId" instead of "EndpointId" update the lambda code accordingly.
